spring.application.name=crud-carros

# H2 Database
spring.web.resources.static-locations=classpath:/static/,file:C:/uploads/
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Habilita o método DELETE via hidden field no form
spring.mvc.hiddenmethod.filter.enabled=true
